# Generated by Django 3.1.3 on 2020-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201224_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='offer',
            field=models.FloatField(),
        ),
    ]
