# Generated by Django 3.1.3 on 2020-12-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201224_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='buyer',
        ),
    ]
