# Generated by Django 3.1.3 on 2020-12-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201224_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='User',
            new_name='user',
        ),
    ]
