# Generated by Django 3.1.3 on 2020-12-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_winneritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WinnerItem',
        ),
    ]
